// Shared inline styles for the console (moved out of App.tsx in Sprint B8 —
// mechanical extraction, §4 file-size rule). Inline styles keep the console
// dependency-free (no CSS framework yet); classNames exist for structure
// tests. Sprint B8 adds the Plugins-pane entries at the bottom.
import type React from 'react';

export const s: Record<string, React.CSSProperties> = {
  shell: { display: 'flex', minHeight: '100vh', fontFamily: 'system-ui, sans-serif', color: '#1a2230' },
  nav: { width: 200, background: '#0f1722', color: '#cdd9e5', padding: 16, display: 'flex', flexDirection: 'column', gap: 4 },
  brand: { fontWeight: 700, fontSize: 14, marginBottom: 12 },
  navItem: { textAlign: 'left', background: 'transparent', border: 'none', color: '#9fb3c8', padding: '8px 10px', borderRadius: 6, cursor: 'pointer', fontSize: 14 },
  navItemActive: { background: '#1d2b3a', color: '#fff' },
  version: { marginTop: 'auto', fontSize: 11, color: '#5b7184' },
  main: { flex: 1, padding: '24px 32px', background: '#f5f7fa' },
  h1: { fontSize: 22, margin: '0 0 12px' },
  h2: { fontSize: 15, margin: '20px 0 8px', color: '#33415c' },
  groupCount: { fontWeight: 400, fontSize: 12, color: '#8195a8' },
  group: { marginBottom: 8 },
  dim: { color: '#5b6b7e', fontSize: 13, margin: '0 0 12px' },
  card: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 8, padding: 14, marginBottom: 10 },
  cardTitle: { fontWeight: 600, marginBottom: 4 },
  caps: { display: 'flex', gap: 16, marginTop: 10, flexWrap: 'wrap' },
  capItem: { minWidth: 80 },
  capKey: { fontSize: 11, color: '#8195a8', textTransform: 'uppercase' },
  capVal: { fontSize: 14 },
  badge: { fontSize: 11, padding: '1px 8px', borderRadius: 10, marginLeft: 6 },
  badgeOnline: { background: '#dcfce7', color: '#166534' },
  badgeStale: { background: '#fef3c7', color: '#92400e' },
  badgeOffline: { background: '#e2e8f0', color: '#475569' },
  badgeApproval: { background: '#e0e7ff', color: '#3730a3' },
  actions: { display: 'flex', gap: 8, marginTop: 12, flexWrap: 'wrap' },
  actionBtn: { background: '#fff', border: '1px solid #cbd5e1', color: '#33415c', padding: '5px 12px', borderRadius: 6, cursor: 'pointer', fontSize: 13 },
  actionPrimary: { background: '#166534', borderColor: '#166534', color: '#fff' },
  actionDanger: { borderColor: '#ef4444', color: '#b91c1c' },
  sampleBanner: { background: '#fef3c7', border: '1px solid #f59e0b', color: '#92400e', borderRadius: 8, padding: '10px 14px', marginBottom: 12, fontSize: 13 },
  errorBanner: { background: '#fee2e2', border: '1px solid #ef4444', color: '#7f1d1d', borderRadius: 8, padding: '10px 14px', marginBottom: 12 },
  secretBanner: { background: '#dcfce7', border: '1px solid #166534', color: '#14532d', borderRadius: 8, padding: '10px 14px', marginBottom: 12 },
  secretCode: { display: 'inline-block', background: '#f0fdf4', border: '1px dashed #166534', borderRadius: 6, padding: '6px 10px', margin: '8px 0', fontSize: 13 },
  secretDismiss: { background: '#166534', border: 'none', color: '#fff', padding: '5px 12px', borderRadius: 6, cursor: 'pointer', fontSize: 13 },
  errorTitle: { fontWeight: 700, fontSize: 14, marginBottom: 4 },
  errorText: { fontSize: 13, margin: '4px 0 0' },

  // --- Plugins pane (Sprint B8) ---------------------------------------------
  pluginMeta: { fontSize: 12, color: '#8195a8', marginBottom: 6 },
  pluginRow: { display: 'flex', gap: 8, alignItems: 'center', marginTop: 10, flexWrap: 'wrap' },
  pluginSelect: { padding: '5px 8px', borderRadius: 6, border: '1px solid #cbd5e1', fontSize: 13, background: '#fff' },
  chip: { display: 'inline-block', fontSize: 12, background: '#e0e7ff', color: '#3730a3', borderRadius: 10, padding: '2px 10px', marginRight: 6, marginBottom: 4 },
  form: { marginTop: 12, display: 'flex', flexDirection: 'column', gap: 8, maxWidth: 480 },
  field: { display: 'flex', flexDirection: 'column', gap: 2 },
  fieldLabel: { fontSize: 13, fontWeight: 600, color: '#33415c' },
  fieldHelp: { fontSize: 11, color: '#8195a8' },
  fieldInput: { padding: '5px 8px', borderRadius: 6, border: '1px solid #cbd5e1', fontSize: 13 },
  fieldGroup: { border: '1px solid #e2e8f0', borderRadius: 6, padding: 10, margin: 0 },
  fieldGroupLegend: { fontSize: 13, fontWeight: 600, color: '#33415c', padding: '0 4px' },
  checkboxRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 },
  advanced: { marginTop: 12 },
  advancedSummary: { cursor: 'pointer', fontSize: 13, color: '#5b6b7e' },
  advancedText: { width: '100%', minHeight: 100, fontFamily: 'monospace', fontSize: 12, marginTop: 8, border: '1px solid #cbd5e1', borderRadius: 6, padding: 8, boxSizing: 'border-box' },
  okBanner: { background: '#dcfce7', border: '1px solid #166534', color: '#14532d', borderRadius: 8, padding: '8px 12px', marginTop: 10, fontSize: 13 },

  // --- Fleet pane node tree (Sprint S4) -------------------------------------
  fleetTree: { display: 'flex', flexDirection: 'column', gap: 0 },
  nodeToggle: { display: 'flex', alignItems: 'baseline', gap: 10, width: '100%', textAlign: 'left', background: 'transparent', border: 'none', padding: 0, cursor: 'pointer', color: '#1a2230' },
  nodeToggleCaret: { color: '#8195a8', fontSize: 12, width: 12 },
  nodeName: { fontWeight: 600, fontSize: 15 },
  nodeSummary: { fontSize: 13, color: '#5b6b7e' },
  nodeFacts: { display: 'flex', flexDirection: 'column', gap: 12, marginTop: 12, paddingTop: 12, borderTop: '1px solid #e2e8f0' },
  factGroup: { minWidth: 120 },
  factLabel: { fontSize: 11, color: '#8195a8', textTransform: 'uppercase', marginBottom: 2 },
  factValue: { fontSize: 14, color: '#1a2230' },
  factSub: { fontSize: 12, color: '#5b6b7e', marginTop: 2 },
  factList: { margin: '2px 0 0', padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 2 },
  factListItem: { fontSize: 14, color: '#1a2230' },
};
